/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { NoContentResult } from '../../models/no-content-result';
import { TimeEntryUpdateReq } from '../../models/time-entry-update-req';

export interface UpdateTimeentryById$Params {
  id: number;
      body: TimeEntryUpdateReq
}

export function updateTimeentryById(http: HttpClient, rootUrl: string, params: UpdateTimeentryById$Params, context?: HttpContext): Observable<StrictHttpResponse<NoContentResult>> {
  const rb = new RequestBuilder(rootUrl, updateTimeentryById.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<NoContentResult>;
    })
  );
}

updateTimeentryById.PATH = '/timeentries/{id}';
