/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ToDo } from '../../models/to-do';

export interface ToDoGet$Params {
  assignee?: string;
  completitionStatus?: boolean;
}

export function toDoGet(http: HttpClient, rootUrl: string, params?: ToDoGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ToDo>>> {
  const rb = new RequestBuilder(rootUrl, toDoGet.PATH, 'get');
  if (params) {
    rb.query('assignee', params.assignee, {});
    rb.query('completitionStatus', params.completitionStatus, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<ToDo>>;
    })
  );
}

toDoGet.PATH = '/to-do';
