/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ToDo } from '../../models/to-do';

export interface ToDoIdGet$Params {
  id: number;
}

export function toDoIdGet(http: HttpClient, rootUrl: string, params: ToDoIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<ToDo>> {
  const rb = new RequestBuilder(rootUrl, toDoIdGet.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ToDo>;
    })
  );
}

toDoIdGet.PATH = '/to-do/{id}';
