/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ToDo } from '../../models/to-do';
import { ToDoCreationDto } from '../../models/to-do-creation-dto';

export interface ToDoIdPatch$Params {
  id: number;
      body: ToDoCreationDto
}

export function toDoIdPatch(http: HttpClient, rootUrl: string, params: ToDoIdPatch$Params, context?: HttpContext): Observable<StrictHttpResponse<ToDo>> {
  const rb = new RequestBuilder(rootUrl, toDoIdPatch.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ToDo>;
    })
  );
}

toDoIdPatch.PATH = '/to-do/{id}';
