/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Product {
  category?: string | null;
  id?: number;
  pricePerUnit?: number;
  productCode?: string;
  productDescription?: string | null;
  productName?: string;
}
