/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { PingGet$Params as PingGet$Params } from './fn/web-api/ping-get';
export { pingGet as pingGet } from './fn/web-api/ping-get';
export type { ListAllTravels$Params as ListAllTravels$Params } from './fn/travels/list-all-travels';
export { listAllTravels as listAllTravels } from './fn/travels/list-all-travels';
export type { GetDetail$Params as GetDetail$Params } from './fn/travels/get-detail';
export { getDetail as getDetail } from './fn/travels/get-detail';
export type { TravelsUploadPost$Params as TravelsUploadPost$Params } from './fn/travels/travels-upload-post';
export { travelsUploadPost as travelsUploadPost } from './fn/travels/travels-upload-post';
