/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { GetAllAppointments$Params as GetAllAppointments$Params } from './fn/appointments/get-all-appointments';
export { getAllAppointments as getAllAppointments } from './fn/appointments/get-all-appointments';
export type { CreateAppointment$Params as CreateAppointment$Params } from './fn/appointments/create-appointment';
export { createAppointment as createAppointment } from './fn/appointments/create-appointment';
export type { GetAppointmentById$Params as GetAppointmentById$Params } from './fn/appointments/get-appointment-by-id';
export { getAppointmentById as getAppointmentById } from './fn/appointments/get-appointment-by-id';
export type { DeleteAppointment$Params as DeleteAppointment$Params } from './fn/appointments/delete-appointment';
export { deleteAppointment as deleteAppointment } from './fn/appointments/delete-appointment';
export type { EstimatePrice$Params as EstimatePrice$Params } from './fn/appointments/estimate-price';
export { estimatePrice as estimatePrice } from './fn/appointments/estimate-price';
