/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { Appointment } from './models/appointment';
export type { AppointmentService } from './models/appointment-service';
export type { StyleReference } from './models/style-reference';
