/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AuthReq } from '../models/auth-req';
export interface ItemPushReq {
  auth: AuthReq;
  category: string;
  name: string;
}
