/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { GiftCategory } from '../models/gift-category';
export interface WishlistItem {
  bought?: boolean;
  category?: GiftCategory;
  id?: number;
  itemName?: string;
}
