/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ItemPushReq } from '../../models/item-push-req';
import { WishlistItem } from '../../models/wishlist-item';

export interface AddItem$Params {
  name: string;
      body: ItemPushReq
}

export function addItem(http: HttpClient, rootUrl: string, params: AddItem$Params, context?: HttpContext): Observable<StrictHttpResponse<WishlistItem>> {
  const rb = new RequestBuilder(rootUrl, addItem.PATH, 'post');
  if (params) {
    rb.path('name', params.name, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<WishlistItem>;
    })
  );
}

addItem.PATH = '/wishlist/{name}/items/add';
