/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { VerifyPin$Params as VerifyPin$Params } from './fn/wishlist-endpoints/verify-pin';
export { verifyPin as verifyPin } from './fn/wishlist-endpoints/verify-pin';
export type { WishlistNameItemsPost$Params as WishlistNameItemsPost$Params } from './fn/wishlist-endpoints/wishlist-name-items-post';
export { wishlistNameItemsPost as wishlistNameItemsPost } from './fn/wishlist-endpoints/wishlist-name-items-post';
export type { MarkAsBought$Params as MarkAsBought$Params } from './fn/wishlist-endpoints/mark-as-bought';
export { markAsBought as markAsBought } from './fn/wishlist-endpoints/mark-as-bought';
export type { DeleteItem$Params as DeleteItem$Params } from './fn/wishlist-endpoints/delete-item';
export { deleteItem as deleteItem } from './fn/wishlist-endpoints/delete-item';
export type { AddItem$Params as AddItem$Params } from './fn/wishlist-endpoints/add-item';
export { addItem as addItem } from './fn/wishlist-endpoints/add-item';
export type { RetrieveGiftCategories$Params as RetrieveGiftCategories$Params } from './fn/wishlist-endpoints/retrieve-gift-categories';
export { retrieveGiftCategories as retrieveGiftCategories } from './fn/wishlist-endpoints/retrieve-gift-categories';
