/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { GetCategories$Params } from './fn/products-endpoints/get-categories';
export { getCategories } from './fn/products-endpoints/get-categories';
export type { GetProducts$Params } from './fn/products-endpoints/get-products';
export { getProducts } from './fn/products-endpoints/get-products';
export type { GetSpecificProduct$Params } from './fn/products-endpoints/get-specific-product';
export { getSpecificProduct } from './fn/products-endpoints/get-specific-product';
export type { UpdateSpecificProduct$Params } from './fn/products-endpoints/update-specific-product';
export { updateSpecificProduct } from './fn/products-endpoints/update-specific-product';
export type { DeleteSpecificProduct$Params } from './fn/products-endpoints/delete-specific-product';
export { deleteSpecificProduct } from './fn/products-endpoints/delete-specific-product';
