/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { CategoryQueryRes } from './models/category-query-res';
export type { Product } from './models/product';
export type { ProductUpdateReq } from './models/product-update-req';
