/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { EmployeeDto } from '../models/employee-dto';
import { ProjectDto } from '../models/project-dto';
export interface TimeEntryUpdateReq {
  date: string;
  description: string;
  employee: EmployeeDto;
  endTime: string;
  project: ProjectDto;
  startTime: string;
}
