/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { ToDoGet$Params } from './fn/to-do-endpoints/to-do-get';
export { toDoGet } from './fn/to-do-endpoints/to-do-get';
export type { ToDoPost$Params } from './fn/to-do-endpoints/to-do-post';
export { toDoPost } from './fn/to-do-endpoints/to-do-post';
export type { ToDoIdGet$Params } from './fn/to-do-endpoints/to-do-id-get';
export { toDoIdGet } from './fn/to-do-endpoints/to-do-id-get';
export type { ToDoIdPut$Params } from './fn/to-do-endpoints/to-do-id-put';
export { toDoIdPut } from './fn/to-do-endpoints/to-do-id-put';
export type { ToDoIdDelete$Params } from './fn/to-do-endpoints/to-do-id-delete';
export { toDoIdDelete } from './fn/to-do-endpoints/to-do-id-delete';
export type { ToDoIdPatch$Params } from './fn/to-do-endpoints/to-do-id-patch';
export { toDoIdPatch } from './fn/to-do-endpoints/to-do-id-patch';
