// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SatisfactoryPlanner.Data;

#nullable disable

namespace SatisfactoryPlanner.Data.Migrations
{
    [DbContext(typeof(ApplicationDataContext))]
    partial class ApplicationDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("ElementLineRecipe", b =>
                {
                    b.Property<Guid>("ElementLinesId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RecipesId")
                        .HasColumnType("TEXT");

                    b.HasKey("ElementLinesId", "RecipesId");

                    b.HasIndex("RecipesId");

                    b.ToTable("ElementLineRecipe");
                });

            modelBuilder.Entity("SatisfactoryPlanner.Data.Element", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Elements");
                });

            modelBuilder.Entity("SatisfactoryPlanner.Data.ElementLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ElementId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ElementId");

                    b.ToTable("ElementLines");
                });

            modelBuilder.Entity("SatisfactoryPlanner.Data.Machine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RecipeId")
                        .HasColumnType("TEXT");

                    b.Property<int>("RecipeLevel")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RecipeType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.ToTable("Machines");
                });

            modelBuilder.Entity("SatisfactoryPlanner.Data.Recipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("RecipeType")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ResultingElementId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ResultingElementId");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("ElementLineRecipe", b =>
                {
                    b.HasOne("SatisfactoryPlanner.Data.ElementLine", null)
                        .WithMany()
                        .HasForeignKey("ElementLinesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SatisfactoryPlanner.Data.Recipe", null)
                        .WithMany()
                        .HasForeignKey("RecipesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SatisfactoryPlanner.Data.ElementLine", b =>
                {
                    b.HasOne("SatisfactoryPlanner.Data.Element", "Element")
                        .WithMany()
                        .HasForeignKey("ElementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Element");
                });

            modelBuilder.Entity("SatisfactoryPlanner.Data.Machine", b =>
                {
                    b.HasOne("SatisfactoryPlanner.Data.Recipe", "Recipe")
                        .WithMany()
                        .HasForeignKey("RecipeId");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("SatisfactoryPlanner.Data.Recipe", b =>
                {
                    b.HasOne("SatisfactoryPlanner.Data.Element", "ResultingElement")
                        .WithMany()
                        .HasForeignKey("ResultingElementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ResultingElement");
                });
#pragma warning restore 612, 618
        }
    }
}
