/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { Employee } from './models/employee';
export type { Employee2 } from './models/employee-2';
export type { EmployeeDto } from './models/employee-dto';
export type { NoContentResult } from './models/no-content-result';
export type { Project } from './models/project';
export type { Project2 } from './models/project-2';
export type { ProjectDto } from './models/project-dto';
export type { TimeEntry } from './models/time-entry';
export type { TimeEntryUpdateReq } from './models/time-entry-update-req';
