/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { StyleReference } from '../models/style-reference';
export interface AppointmentService {
  appointmentId?: number;
  id?: number;
  name?: string;
  styleReference?: StyleReference;
}
