/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AppointmentService } from '../models/appointment-service';
export interface Appointment {
  barberName?: string | null;
  beverageChoice?: string | null;
  customerName?: string;
  date?: string;
  duration?: string;
  id?: number;
  isVip?: boolean;
  services?: Array<AppointmentService>;
  startTime?: string;
}
